# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        # exclude docs/ tests/ and .github/ directories
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - "commit"
    -   id: end-of-file-fixer
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - "commit"
    -   id: check-yaml
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - "commit"
    -   id: check-added-large-files
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - "commit"

-   repo: local
    hooks:
    -   id: format
        name: Running make format
        entry: ./scripts/format_and_add.sh
        language: script
        pass_filenames: false
        stages:
          - "commit"
    -   id: lint
        name: Running make lint
        entry: make lint
        language: system
        pass_filenames: false
        stages:
          - "commit"
    -   id: copyright
        name: Running make copyright
        entry: make copyright
        language: system
        pass_filenames: false
        stages:
          - "commit"
    # -   id: git-add
    #     name: Add formatted files
    #     entry: git add -u
    #     language: system
    #     always_run: true
    #     pass_filenames: false
    #     stages:
    #       - "commit"
