# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
        # exclude docs/ tests/ and .github/ directories
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - 'commit'
      - id: end-of-file-fixer
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - 'commit'
      - id: check-yaml
        exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
        stages:
          - 'commit'
      # Disabling while we do notebooks directory cleanup
      # - id: check-added-large-files
      #   args: [--maxkb=1024]
      #   exclude: ^(.*/)?(docs|tests|\.github)(/.*)?$
      #   stages:
      #     - "commit"

  - repo: local
    hooks:
      - id: check_for_notebook_outputs
        name: Check for notebook outputs
        entry: make ensure-clean-notebooks
        language: system
        # only run if there are .ipynb files in the commit
        types: [jupyter]
        stages:
          - 'pre-commit'
      - id: check_for_credentials
        name: Check for exposed credentials
        entry: make verify-exposed-credentials
        language: system
        # only run if there are .ipynb files in the commit
        types: [jupyter]
        stages:
          - 'pre-commit'
      - id: generate_test_id_types
        name: Running make generate_test_id_types
        entry: make generate-test-id-types
        language: system
        pass_filenames: false
        stages:
          - 'commit'
      - id: format
        name: Running make format
        entry: ./scripts/format_and_add.sh
        language: script
        pass_filenames: false
        stages:
          - 'commit'
      - id: lint
        name: Running make lint
        entry: make lint
        language: system
        pass_filenames: false
        stages:
          - 'push'
