[tool.poetry]
authors = ["Andres Rodriguez <andres@validmind.ai>"]
description = "ValidMind SDK"
name = "validmind"
version = "1.2.8"

[tool.poetry.dependencies]
click = "^8.0.4"
dython = "^0.7.1"
ipython = "^8.11.0"
myst-parser = "^1.0.0"
numpy = "1.22.3"
pandas = "1.3.5"
pandas-profiling = "^3.2.0"
pydantic = "^1.9.1"
pypmml = "^0.9.17"
python = ">=3.8,<3.11"
python-dotenv = "^0.20.0"
requests = "^2.27.1"
rpy2 = {version = "^3.5.10", optional = true}
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
shap = "^0.41.0"
sphinx = "^6.1.3"
sphinx-markdown-builder = "^0.5.5"
sphinx-rtd-theme = "^1.2.0"
statsmodels = "^0.13.5"
tabulate = "^0.8.9"
tqdm = "^4.64.0"
xgboost = "^1.5.2"
arch = "^5.4.0"

[tool.poetry.group.dev.dependencies]
black = "^22.1.0"
click = "^8.1.3"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
pytest = "^5.2"

[tool.poetry.extras]
r-support = ["rpy2"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
