[tool.poetry]
authors = ["Andres Rodriguez <andres@validmind.ai>"]
description = "ValidMind SDK"
name = "validmind-sdk"
version = "0.1.0"

[tool.poetry.dependencies]
click = "^8.0.4"
ipykernel = "^6.9.0"
jupyter = "^1.0.0"
lightgbm = "^3.3.2"
matplotlib = "^3.5.1"
notebook = "^6.4.8"
numpy = "^1.22.2"
pandas = "1.3.5"
python = ">=3.8,<3.11"
python-dotenv = "^0.20.0"
requests = "^2.27.1"
scikit-learn = "^1.0.2"
scipy = "1.8.0"
xgboost = "^1.5.2"
pandas-profiling = "^3.2.0"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
