[tool.poetry]
authors = ["Andres Rodriguez <andres@validmind.ai>"]
description = "ValidMind SDK"
name = "validmind"
version = "1.1.1"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
click = "^8.0.4"
dython = "^0.7.1"
numpy = "1.22.3"
pandas = "1.3.5"
pydantic = "^1.9.1"
python-dotenv = "^0.20.0"
requests = "^2.27.1"
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
shap = "^0.41.0"
tabulate = "^0.8.9"
tqdm = "^4.64.0"
xgboost = "^1.5.2"
statsmodels = "^0.13.5"
pandas-profiling = "^3.2.0"
ipython = "^8.11.0"

[tool.poetry.group.r_support]
optional = true

[tool.poetry.group.r_support.dependencies]
rpy2 = "^3.4.5"
pypmml = "^0.9.17"

[tool.poetry.extras]
r_support = ["rpy2", "pypmml"]

[tool.poetry.dev-dependencies]
black = "^22.1.0"
click = "^8.1.3"
flake8 = "^4.0.1"
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
