[tool.poetry]
authors = ["Andres Rodriguez <andres@validmind.ai>"]
description = "ValidMind SDK"
name = "validmind"
version = "0.8.1"

[tool.poetry.dependencies]
click = "^8.0.4"
ipykernel = "^6.9.0"
jupyter = "^1.0.0"
lightgbm = "^3.3.2"
notebook = "^6.4.8"
numpy = "1.21.6"
pandas = "1.3.5"
pandas-profiling = "^3.2.0"
pydantic = "^1.9.1"
python = ">=3.7,<3.11"
python-dotenv = "^0.20.0"
requests = "^2.27.1"
scikit-learn = "^1.0.2"
tabulate = "^0.8.9"
tqdm = "^4.64.0"
wheel = "^0.37.1"
xgboost = "^1.5.2"
seaborn = "^0.11.2"
shap = "^0.41.0"
dython = "^0.7.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
imbalanced-learn = "0.8.1"
jupyterlab = "^3.4.3"
pytest = "^5.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
